CREATE DATABASE servletjsp;
USE servletjspjdbc;
CREATE TABLE IF NOT EXISTS contact (
	id INT NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	mobile_number VARCHAR(255) NOT NULL,
	email_address VARCHAR(255) NULL,
	address VARCHAR(255) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);